### ISSUE TITLE
Compatibility with IE browser

### ISSUE THREAD

**Issue by madhu-aithal** [project-sunbird/sunbird-telemetry-sdk#3]
If I try to use this telemetry SDK in Internet Explorer browser (I am using IE 11), I am getting the below error

` ERROR TypeError: Object doesn't support this action`

Below is the complete stacktrace of the error
```
TypeError: Object doesn't support this action
   at libraryDispatcher.dispatch (http://localhost:4200/vendor.js:67373:13)
   at Anonymous function (http://localhost:4200/vendor.js:67727:25)
   at Anonymous function (http://localhost:4200/vendor.js:67859:21)
   at Anonymous function (http://localhost:4200/assets/js/telemetry.js:4525:17)
   at Anonymous function (http://localhost:4200/assets/js/telemetry.js:4759:21)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:7945:13)
   at onInvokeTask (http://localhost:4200/vendor.js:49534:17)
   at ZoneDelegate.prototype.invokeTask (http://localhost:4200/polyfills.js:7945:13)
   at Zone.prototype.runTask (http://localhost:4200/polyfills.js:7718:21)
   at ZoneTask.invokeTask (http://localhost:4200/polyfills.js:8021:17)```

**Comment by manjudr** [comment]
@madhu-aithal  I
Is library dispatcher instance is available? Are you overriding the library dispatcher ? what configurations are you passing ?

**Comment by madhu-aithal** [comment]
@manjudr 
I am not overriding the library dispatcher. I am passing values for `uid`, `pdata`, `batchsize`, `host`, `endpoint`, `apislug` (empty value), `env` in the configuration object.

**Comment by madhu-aithal** [comment]
@manjudr 
When I debugged the issue, I found out it was because of dispatching custom events (line 18 of `telemetryV3Interface.js`).  `CustomEvent` does not seem to work in IE browsers. 

So If I make the following change in line 18 of `telemetryV3Interface.js`, it is working fine.

Before
`document.dispatchEvent(new CustomEvent('TelemetryEvent', { detail: event }));` 

After
`
const customEvent = document.createEvent("CustomEvent");    
customEvent.initCustomEvent('TelemetryEvent', false, false, {
detail: event,
});            
document.dispatchEvent(customEvent);`

I have also created a pull request for the same. Please let me know if it is correct.
